chore: demonstrate #306
yearn/yearn-vaults pull request #307
Opened 2021-04-30 00:52 UTC by fp-crypto

2021-04-30 01:30 UTC, poolpitako approved these changes

2021-04-30 01:30 UTC, poolpitako commented on tests/functional/vault/test_losses.py
> +    chain.sleep(DAY // 10)
you can remove this.

2021-04-30 01:30 UTC, poolpitako commented on tests/functional/vault/test_losses.py
> +    token.approve(strategy, 2 ** 256 - 1, {"from": strategy})
you don't need this either.

2021-04-30 01:30 UTC, poolpitako commented on tests/functional/vault/test_losses.py
> +    chain.sleep(DAY // 10)
no op. you can remove.

2021-04-30 01:30 UTC, poolpitako commented on tests/functional/vault/test_losses.py
> +    params = vault.strategies(strategy).dict()
unused

2021-04-30 01:30 UTC, poolpitako commented on tests/functional/vault/test_losses.py
> +    chain.sleep(DAY // 10)
you can remove this as well. sorry.

2021-04-30 01:30 UTC, poolpitako commented on tests/functional/vault/test_losses.py
> +    assert params["totalDebt"] == 0
also `assert params["debtRatio"] == 0`

2021-04-30 20:22 UTC, fubuloubu approved these changes
Please fix your commit messages to align with conventional commits and run `black .` on your code updates to get this to pass the CI

2021-05-01 17:54 UTC, fubuloubu requested changes
The issue here is that the actual bug is that the loss is accounted for before this ratio adjustment calculation is computed. That should be re-ordered to occur prior to the subtraction of the loss.

2021-05-03 17:34 UTC, fubuloubu commented
This would be my suggestion for how to change this PR
```diff
  def _reportLoss(strategy: address, loss: uint256):
      # Loss can only be up the amount of debt issued to strategy
      totalDebt: uint256 = self.strategies[strategy].totalDebt
      assert totalDebt >= loss
+ 
+     # Also, make sure we reduce our trust with the strategy by the amount of loss
+     precisionFactor: uint256 = self.precisionFactor
+     ratio_change: uint256 = min(
+         precisionFactor * MAX_BPS * loss / totalDebt / precisionFactor,
+         self.strategies[strategy].debtRatio,
+    )
+ 
+    # Finally, adjust our strategy's parameters by the loss
      self.strategies[strategy].totalLoss += loss
      self.strategies[strategy].totalDebt = totalDebt - loss
      self.totalDebt -= loss
-     # Also, make sure we reduce our trust with the strategy by the same amount
-     debtRatio: uint256 = self.strategies[strategy].debtRatio
-     precisionFactor: uint256 = self.precisionFactor
-     ratio_change: uint256 = min(precisionFactor * loss * MAX_BPS / self._totalAssets() / precisionFactor, debtRatio)
      self.strategies[strategy].debtRatio -= ratio_change
      self.debtRatio -= ratio_change
```

2021-05-04 15:07 UTC, fubuloubu commented
Suggested change to ensure that this value is not user-manipulatable.

```python
  ratio_change: uint256 = min(
        precisionFactor * MAX_BPS * loss / self.totalDebt * MAX_BPS / self.debtRatio / precisionFactor,
        self.strategies[strategy].debtRatio,
   )
```

2021-05-10 10:51 UTC, steffenix commented
@fp-crypto need help?

2021-05-12 08:10 UTC, steffenix commented
Will take care of it.

2021-05-12 08:10 UTC, steffenix commented
Will take care of it.

2021-05-12 08:10 UTC, closed without merging