chore: bump vyper version
yearn/yearn-vaults pull request #355
Opened 2021-05-18 06:13 UTC by steffenix

2021-05-18 15:16 UTC, fubuloubu commented
Do we want to update the 0.4.0 tag for this?

2021-05-18 15:16 UTC, fubuloubu approved these changes

2021-05-18 15:16 UTC, fubuloubu requested changes

2021-05-18 15:16 UTC, fubuloubu commented on contracts/Registry.vy
> +# @version 0.2.12
Can't update the Registry

2021-05-18 16:17 UTC, steffenix commented
> Do we want to update the 0.4.0 tag for this?

I am thinking we should tag 0.4 with that

2021-05-18 18:33 UTC, fubuloubu commented
> > Do we want to update the 0.4.0 tag for this?
> 
> I am thinking we should tag 0.4 with that

Let's do it!

Just not the Registry lol

2021-05-18 21:24 UTC, steffenix commented
> > > Do we want to update the 0.4.0 tag for this?
> > 
> > 
> > I am thinking we should tag 0.4 with that
> 
> Let's do it!
> 
> Just not the Registry lol

What's about Registry? Just don't need to redeploy it or something will breek?

2021-05-19 02:42 UTC, fubuloubu commented
> What's about Registry? Just don't need to redeploy it or something will breek?

Upgrading the Registry requires replaying all of the events in the previous version of the registry, as well as coordinating upgrades across all AffiliateWrappers and yTokens (which aren't deployed yet)

2021-05-19 08:17 UTC, steffenix commented
I do not understand why we can't bump the Registry version we just don't deploy it again.

2021-05-19 15:20 UTC, fubuloubu commented
> I do not understand why we can't bump the Registry version we just don't deploy it again.

We can deploy it again, its just the deployment process is much more involved than with a new `Vault` API version. There are many downstrram users of the registry that would need to be updated, and a large amount of transactions that need to be replayed on the newly deployed registry (20+ transactions)

Its possible, but not very simple, and not really worth it just to upgrade the compiler version, unless a critical bug were found or there was a new feature we needed.

2021-05-19 15:48 UTC, steffenix commented
@fubuloubu I have made the update

2021-05-19 16:26 UTC, fubuloubu approved these changes

2021-05-19 16:43 UTC, merged