chore: add Slither analyzer
yearn/yearn-vaults pull request #520
Opened 2022-02-10 16:13 UTC by fubuloubu

fixes: #478

2022-02-11 02:24 UTC, sambacha requested changes
https://github.com/yearn/yearn-vaults/pull/521/files#diff-245392b692a50c38ecab4381b118862db514035c10983f3bd4f4b7f1f4be4692R150

this will cause this CI process to always fail, as slither will exit with an error if it finds anything, and it will.

see my PR here https://github.com/yearn/yearn-vaults/pull/521 

we can close this thx

2022-02-11 15:09 UTC, arvatran commented
It should be possible to ignore the result with a github config, the option here is much simple that what you have made @sambacha

2022-02-11 15:16 UTC, sambacha commented
> Seems easier to use `crytic/slither-action@v0.1.0` than your changes @sambacha 
> 
> I will see if we can make crytic/slither-action@v0.1.0` not to fail with a variable

My PR is exactly that 😘

2022-02-20 05:34 UTC, pandadefi approved these changes

2022-02-20 05:56 UTC, merged